version: "3.1"
services:

    mysql:
        image: mysql
        container_name: newtech-mysql
        entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_ALLOW_EMPTY_PASSWORD: y
        volumes:
            - ./docker/_data/mysql-data/db:/var/lib/mysql #mysql-data
        networks:
            - mrede

    webserver:
      image: nginx:alpine
      container_name: newtech-webserver
      working_dir: /var/www/html/
      volumes:
          - .:/var/www/html/
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      networks:
        - mrede

    php-fpm:
      image: php:7.2-fpm
      container_name: newtech-php-fpm
      working_dir: /var/www/html/
      volumes:
        - .:/var/www/html/
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - mrede
networks: 
    mrede: